CREATE TABLE IF NOT EXISTS Statuses
(
  id int(11) PRIMARY KEY AUTO_INCREMENT,
  username varchar(255) NOT NULL,
  content varchar(255),
  date DATETIME
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Users
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  login VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
)ENGINE=InnoDB;